import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const StoreProvider = dynamic(() => import("./StoreProvider"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <StoreProvider>
          <MantineProvider>{children}</MantineProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
