import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { MantineEmotionProvider, emotionTransform } from "@mantine/emotion";
import { ModalsProvider } from "@mantine/modals";
import { Notifications } from "@mantine/notifications";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import { RootStyleRegistry } from "./EmotionRootStyleRegistry";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const StoreProvider = dynamic(() => import("./StoreProvider"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <StoreProvider>
          <RootStyleRegistry>
            <MantineEmotionProvider>
              <MantineProvider stylesTransform={emotionTransform}>
                <Notifications />
                <ModalsProvider>{children}</ModalsProvider>
              </MantineProvider>
            </MantineEmotionProvider>
          </RootStyleRegistry>
        </StoreProvider>
      </body>
    </html>
  );
}
